// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RedisCache is an autogenerated mock type for the RedisCache type
type RedisCache struct {
	mock.Mock
}

// Del provides a mock function with given fields: key
func (_m *RedisCache) Del(key string) {
	_m.Called(key)
}

// Get provides a mock function with given fields: key
func (_m *RedisCache) Get(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Set provides a mock function with given fields: key, value
func (_m *RedisCache) Set(key string, value interface{}) {
	_m.Called(key, value)
}

type mockConstructorTestingTNewRedisCache interface {
	mock.TestingT
	Cleanup(func())
}

// NewRedisCache creates a new instance of RedisCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRedisCache(t mockConstructorTestingTNewRedisCache) *RedisCache {
	mock := &RedisCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
